branches:
  only:
  - v3

dist: xenial

language: node_js

matrix:
  include:
  - os: linux
    node_js: 8
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - g++-4.9
    env:
    - CC="gcc-4.9"
    - CXX="g++-4.9"
  - os: linux
    node_js: 10
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - g++-7
    env:
    - CC="gcc-7"
    - CXX="g++-7"
  - os: linux
    node_js: 12
    addons:
      apt:
        sources:
        - llvm-toolchain-xenial-7
        packages:
        - clang-7
    env:
    - CC="clang-7"
    - CXX="clang++-7"

install:
- npm install

script:
- npm run lint
- npm test

notifications:
  email:
    recipients:
    - secure: foUoGDMyhU89TRM4ivj1VdNamvNu0lOU/z3ca5sT7vmyqyVN54efC/g0glXKyPx8UgiV1fsYUcgnjUz3UABvenloMe4bMbt7whq1WzLYizIoaUFxX79xEAsTJ6IQbqyXUkUoClAUOxsiat+nohF6jbfwukJfpkFqVi53CxnCFG0=
    - secure: Xhcxa2H3pBGd7pn6G7UPntdlhCoF6dULRmJGlqwwB+Pthz4ZpGGiI8LWh56A2lZcIjJjpmOKYHPFKN8kyyoYdcfrIY0DdiBKJiKfVObpLYm4+o9V8q6J7VxZ9MJ0YAY87aLM9oj+xKe6iWdccVAKNLph/J8Ux8R/0+41dbbHqic=
    on_success: change
    on_failure: always
